resolves issue #200 enables webhook commands on subgroups
mattermost/mattermost-plugin-gitlab pull request #202
Opened 2020-09-07 13:28 UTC by ericjaystevens

#### Summary

Enables support for manages group scopes webhooks in subgroups and project scope webhooks in projects that are inside a subgroup.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-plugin-gitlab/issues/200

2020-09-09 20:57 UTC, hanzei approved these changes
Thanks for the fix :+1: 

Two suggestions, but nothing blocking.

2020-09-09 20:57 UTC, hanzei commented on server/command.go
> +		if namespaceErr != nil {
Nit: Should this name just be `err` as it's idiomatic?

2020-09-09 20:57 UTC, hanzei commented on server/command.go
> -		// If webhook is group scoped
Nit: Maybe keep this comment instead of adding a new one? #reducethediff

2020-09-20 01:00 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich

2020-09-21 12:09 UTC, hanzei commented
@larkox Could you please review this PR while @iomodo is OOO?

2020-09-22 11:17 UTC, larkox requested changes
LGTM, but I want to make sure about a small detail.

2020-09-22 11:17 UTC, larkox commented on server/command.go
> +			project, _ := p.GitlabClient.GetProject(info, group, projectName)
Why are we not checking this error?

2020-09-28 21:33 UTC, storrgie commented
Is possible to get some love on this? We've got a pretty deep structure in gitlab that we want to use this bot with. We're new licensees of both gitlab ultimate and mattermost e20.

2020-09-28 21:58 UTC, hanzei commented
@ericjaystevens Would you mind adding the error check for https://github.com/mattermost/mattermost-plugin-gitlab/pull/202#discussion_r492654104? Let me know if you need help.

2020-10-03 10:40 UTC, hanzei approved these changes

2020-10-05 09:40 UTC, larkox approved these changes
LGTM, thanks!

2020-10-16 12:08 UTC, storrgie commented
Again tapping to see if this can get some love. We can't use the plugin with gitlab at this time (all of our repositories are located 2+ levels down in organizational structure).

2020-10-18 18:10 UTC, jasonblais commented
@DHaussermann kind reminder to help with QA review, thanks! :)

2020-10-19 17:11 UTC, DHaussermann reviewed
Tested and passed
- Confirmed that creating a webhook with the slash command works as expected within a sub-group
- Brief regression testing to ensure `private` flag of the project is respected and event delivery is working 
- No issues found

LGTM!

Added release test to cover this sub-group case.

Thanks @ericjaystevens for addressing this. Much appreciated!

2020-10-19 17:18 UTC, DHaussermann approved these changes

2020-10-21 11:37 UTC, merged