support FreeBSD
mattermost/mattermost-plugin-gitlab pull request #241
Opened 2021-01-22 01:31 UTC by swills

2021-01-22 01:31 UTC, mattermod commented
Hello @swills,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-02-05 16:55 UTC, hanzei requested changes
Thanks for the contribution :+1: 

Could you elaborate a bit why you think this change should go into `master`? The Mattermost Marketplace is the default way to install plugin and it doesn't support FreeBSD any way. Who is the audience for this change?

2021-02-19 01:00 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-05-27 09:41 UTC, lindy65 commented
Hi @swills - I'm helping to review stale PRs and, since we haven't heard from you in a few months, I'll close this PR for now. Please feel free to re-open if you're able to prioritize. Thanks!

//cc @hanzei

2021-05-27 09:41 UTC, closed without merging