[issue 194] Closing issues or merge requests does not create an event post with a link back to the project #194
mattermost/mattermost-plugin-gitlab pull request #285
Opened 2022-04-03 15:15 UTC by sibasankarnayak

added proper link on notification on PR (close , open, reopen) and issue (close, repoen)

ticket here

Fixes #194

2022-04-03 15:15 UTC, mattermod commented
Hello @sibasankarnayak,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-04-21 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2022-04-27 19:48 UTC, mickmister requested changes

2022-04-27 19:48 UTC, mickmister commented on server/webhook/issue.go
> +		message = fmt.Sprintf("[%s](%s) Issue [%s](%s) closed by [%s](%s)", repo.PathWithNamespace, repo.GitHTTPURL, issue.Title, issue.URL, senderGitlabUsername, w.gitlabRetreiver.GetUserURL(senderGitlabU
`GitHTTPURL` seems like the wrong one to use here. Let's use `WebURL` instead

2022-05-02 10:22 UTC, hanzei commented
/update-branch

2022-05-02 10:22 UTC, mattermod commented
We don't have permissions to update this PR, please contact the submitter to apply the update.

2022-05-06 17:08 UTC, mickmister approved these changes

2022-05-17 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2022-09-18 06:37 UTC, hanzei approved these changes

2022-09-29 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-02-21 07:35 UTC, hanzei commented
@DHaussermann Gentle reminder to review the PR

2023-03-03 17:36 UTC, DHaussermann approved these changes
Tested and passed
For both issues and PRs - the project is now a link.
Ensured links are functional

LGTM!

2023-03-04 09:03 UTC, merged