PR for discussion: Verbose logging for token debugging
mattermost/mattermost-plugin-gitlab pull request #422
Opened 2023-12-15 11:10 UTC by mickmister

#### Summary

Relevant threads
https://community.mattermost.com/core/pl/prbb563aqbrxxjz1qsihz4i44y
https://community.mattermost.com/core/pl/5khxy7mqxi8pijprf7rid8nyuc

#### Ticket Link

2023-12-15 11:22 UTC, mickmister commented on server/api.go
> +		}
We can use this to set the expiry of the user's token. Run this in the browser dev console to set the expiry to 1 minute ot 0 minutes:

```js
// set to 1 minute
fetch('/plugins/com.github.manland.mattermost-plugin-gitlab/set-expiry?expiry=1')
```

```js
// set to 0 minutes
fetch('/plugins/com.github.manland.mattermost-plugin-gitlab/set-expiry?expiry=0');


```

2023-12-18 14:15 UTC, hanzei requested changes
I see the value in logging the tokens. What is the deal with all of the `calling XYZ` calls? At that point, you might as well add a stacktrace.

2023-12-18 14:15 UTC, hanzei commented on server/command_test.go
> +			defer mockCtrl.Finish()
Woops

2024-01-15 17:27 UTC, raghavaggarwal2308 commented on server/plugin.go
> +	log.Debugf("end of getOrRefreshTokenWithMutex")
I think we can keep only one log statement from these two

2024-01-15 17:27 UTC, raghavaggarwal2308 commented on server/gitlab/api.go
> +		"token":          MakeSanitizedTokenLogContext(token),
We can log only one of original token and token

2024-01-15 17:27 UTC, raghavaggarwal2308 commented on server/plugin.go
> +	log.Debugf("end of getOrRefreshTokenWithMutex")
Similar pattern is repeated at many places

2024-03-28 13:41 UTC, closed without merging