refactor: convert rhs_sidebar component to ts
mattermost/mattermost-plugin-gitlab pull request #527
Opened 2024-10-01 05:42 UTC by hereje

#### Summary

refactor: convert rhs_sidebar component to ts

- convert component to ts
- update types

#### Ticket Link

Fixes: #425

2024-10-09 07:43 UTC, raghavaggarwal2308 requested changes
@hereje Mostly looks good to me. Just one small comment for discussion.

2024-10-09 07:43 UTC, raghavaggarwal2308 commented on webapp/src/components/rhs_sidebar/rhs_sidebar.tsx
> +    currentChannelId: string,
These fields were not required earlier and I think they can be undefined. What are your opinions on this?

2024-10-10 05:56 UTC, raghavaggarwal2308 approved these changes
LGTM, thanks for your contribution!

2024-10-22 12:50 UTC, wiggin77 approved these changes

2024-10-24 05:33 UTC, hereje commented
> Thanks @hereje. There are some linter issues with this PR. Will you be able to address?

Done!

2024-10-29 18:26 UTC, wiggin77 commented
/update-branch

2024-10-29 18:26 UTC, mattermost-build commented
Error trying to update the PR.
Please do it manually.

2024-10-29 18:36 UTC, wiggin77 commented
@raghavaggarwal2308 can you help get past the CI errors?

2024-11-10 01:04 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-11-18 08:33 UTC, Kshitij-Katiyar commented
@hereje Can you please sync this PR with the latest master? This will fix the failing CI

2025-01-15 20:00 UTC, wiggin77 approved these changes

2025-01-15 20:00 UTC, wiggin77 commented
/update-branch

2025-01-26 01:04 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2025-01-30 09:26 UTC, AayushChaudhary0001 approved these changes
This PR has been tested and one issue was found during this. But on further testing, it was found that the same issue exists on master branch also. So, a new issue will be logged for this. Rest everything looks working fine for the code changes in LHS, LGTM. Approved.

2025-01-30 12:20 UTC, raghavaggarwal2308 commented
@hereje Can you please resolve the conflicts on this PR?

2025-02-10 01:05 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2025-02-18 08:33 UTC, merged